name: Acceptance Tests

on:
  pull_request_target:
    branches:
      - 'master'

jobs:
  jsonnetsyntax:
    name: Jsonnet Syntax
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Base
      # https://github.com/marketplace/actions/checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.repo.full_name }}
        path: base
    - name: Checkout Fork
      # https://github.com/marketplace/actions/checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: fork
    - name: Install Jsonnet
      run: sudo apt-get install -y jsonnet
    - name: Test Syntactic Validity
      run: ./base/.github/render_json.sh ./fork/jsonnet ./fork/json

  jsonnetfmt:
    name: Jsonnet Formatting
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Base
      # https://github.com/marketplace/actions/checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.repo.full_name }}
        path: base
    - name: Checkout Fork
      # https://github.com/marketplace/actions/checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: fork
    - name: Install Jsonnet
      run: sudo apt-get install -y jsonnet
    - name: Test Jsonnet Formatting
      run: ./base/.github/jsonnet_format_check.sh ./fork

  jsondiff:
    name: Show JSON Diff
    runs-on: ubuntu-20.04
    needs:
    - jsonnetsyntax
    - jsonnetfmt
    steps:
    - name: Checkout Base
      # https://github.com/marketplace/actions/checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.repo.full_name }}
        path: base
    - name: Checkout Fork
      # https://github.com/marketplace/actions/checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: fork
    - name: Install Jsonnet
      run: sudo apt-get install -y jsonnet
    - name: Render JSON
      run: ./base/.github/render_json.sh ./fork/jsonnet ./fork/json
    - name: Show JSON Diff
      run: ./base/.github/json_diff_pr_comment.sh ./fork
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
