name: Acceptance Tests

on:
  pull_request_target:
    branches:
      - 'master'

jobs:
  jsonnetsyntax:
    name: Jsonnet Syntax
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Base
      run: git clone --depth 1 ${{ github.event.pull_request.base.repo.html_url }} --branch ${{ github.event.pull_request.base.ref }} base
    - name: Checkout Head
      run: git clone --depth 1 ${{ github.event.pull_request.head.repo.html_url }} --branch ${{ github.event.pull_request.head.ref }} head
    - name: Install Jsonnet
      run: sudo apt-get install -y jsonnet
    - name: Test Syntactic Validity
      run: ./base/.github/render_json.sh ./head/jsonnet ./head/json

  jsonnetfmt:
    name: Jsonnet Formatting
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Base
      run: git clone --depth 1 ${{ github.event.pull_request.base.repo.html_url }} --branch ${{ github.event.pull_request.base.ref }} base
    - name: Checkout Head
      run: git clone --depth 1 ${{ github.event.pull_request.head.repo.html_url }} --branch ${{ github.event.pull_request.head.ref }} head
    - name: Install Jsonnet
      run: sudo apt-get install -y jsonnet
    - name: Test Jsonnet Formatting
      run: ./base/.github/jsonnet_format_check.sh ./head

  jsondiff:
    name: Show JSON Diff
    runs-on: ubuntu-20.04
    needs:
    - jsonnetsyntax
    - jsonnetfmt
    steps:
    - name: Checkout Base
      run: git clone --depth 1 ${{ github.event.pull_request.base.repo.html_url }} --branch ${{ github.event.pull_request.base.ref }} base
    - name: Checkout Head
      run: git clone --depth 1 ${{ github.event.pull_request.head.repo.html_url }} --branch ${{ github.event.pull_request.head.ref }} head
    - name: Install Jsonnet
      run: sudo apt-get install -y jsonnet
    - name: Render JSON
      run: ./base/.github/render_json.sh ./head/jsonnet ./head/json
    - name: Show JSON Diff
      run: ./base/.github/json_diff_pr_comment.sh ./head
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
