name: CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  jsonnetfmt:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v2

    # https://github.com/marketplace/actions/jsonnetfmt
    # Need to make sure that there's at least one *.jsonnet file otherwise
    # this step fails
    - uses: kakkoyun/action-jsonnetfmt@v0.1.1-alpha
